services:
  backend:
    build: ./backend
    container_name: privacy_backend
    restart: always
    env_file:
      - backend/.env
    volumes:
      - ./backend/data:/app/data
      - ./backend/models:/app/models
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: privacy_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

